// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSImCVbcF7RFfVJdQA7fv8YIOYqfkG9MM',
    appId: '1:530290629427:web:30c9019d33a91946a4bc46',
    messagingSenderId: '530290629427',
    projectId: 'autoarchive-eaf9d',
    authDomain: 'autoarchive-eaf9d.firebaseapp.com',
    storageBucket: 'autoarchive-eaf9d.firebasestorage.app',
    measurementId: 'G-84QVBMGGT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CB6oiJncYrLGGVMOFV8zeahkppibLcQ',
    appId: '1:530290629427:android:53e51c7814097369a4bc46',
    messagingSenderId: '530290629427',
    projectId: 'autoarchive-eaf9d',
    storageBucket: 'autoarchive-eaf9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIuT7ZpDvQ-FBswhZwIYmT5T296tpLtM8',
    appId: '1:530290629427:ios:6a7dcbec535e373ba4bc46',
    messagingSenderId: '530290629427',
    projectId: 'autoarchive-eaf9d',
    storageBucket: 'autoarchive-eaf9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectQ1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIuT7ZpDvQ-FBswhZwIYmT5T296tpLtM8',
    appId: '1:530290629427:ios:6a7dcbec535e373ba4bc46',
    messagingSenderId: '530290629427',
    projectId: 'autoarchive-eaf9d',
    storageBucket: 'autoarchive-eaf9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectQ1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSImCVbcF7RFfVJdQA7fv8YIOYqfkG9MM',
    appId: '1:530290629427:web:3e2048a60ebf8ff2a4bc46',
    messagingSenderId: '530290629427',
    projectId: 'autoarchive-eaf9d',
    authDomain: 'autoarchive-eaf9d.firebaseapp.com',
    storageBucket: 'autoarchive-eaf9d.firebasestorage.app',
    measurementId: 'G-QXVTE53MPD',
  );
}
